"use client";

import React from "react";
import { X, Laptop } from "lucide-react";

interface PairNodeModalProps {
  isOpen: boolean;
  pairForm: {
    nodeCode: string;
    name: string;
    machineFingerprint: string;
  };
  setPairForm: React.Dispatch<React.SetStateAction<any>>;
  currentTenant: string;
  currentBranch: string;
  onClose: () => void;
  onSubmit: (e: React.FormEvent) => void;
}

export function PairNodeModal({
  isOpen,
  pairForm,
  setPairForm,
  currentTenant,
  currentBranch,
  onClose,
  onSubmit,
}: PairNodeModalProps) {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-60 bg-slate-900/60 backdrop-blur-sm flex items-center justify-center p-4 animate-fadeIn">
      <div className="bg-white rounded-2xl shadow-2xl max-w-lg w-full border border-slate-200 overflow-hidden">
        <div className="px-6 py-4 bg-slate-900 text-white flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Laptop className="w-5 h-5 text-blue-400" />
            <h3 className="font-bold text-sm">Pair Windows Academic Node</h3>
          </div>
          <button
            onClick={onClose}
            className="text-slate-400 hover:text-white p-1"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        <form onSubmit={onSubmit} className="p-6 space-y-4 text-xs">
          <div className="space-y-1">
            <label className="text-slate-700 font-bold">Node Identifier Code *</label>
            <input
              type="text"
              required
              value={pairForm.nodeCode}
              onChange={(e) => setPairForm({ ...pairForm, nodeCode: e.target.value.toUpperCase() })}
              className="w-full bg-white border border-slate-300 rounded-lg px-3 py-2 text-slate-900 font-mono font-bold focus:ring-1 focus:ring-blue-500"
              placeholder="NODE-PUNE-01"
            />
          </div>

          <div className="space-y-1">
            <label className="text-slate-700 font-bold">Friendly Terminal Name *</label>
            <input
              type="text"
              required
              value={pairForm.name}
              onChange={(e) => setPairForm({ ...pairForm, name: e.target.value })}
              className="w-full bg-white border border-slate-300 rounded-lg px-3 py-2 text-slate-900 focus:ring-1 focus:ring-blue-500"
              placeholder="Kothrud Lab 1 Scanner PC"
            />
          </div>

          <div className="space-y-1">
            <label className="text-slate-700 font-bold">Hardware Machine Fingerprint *</label>
            <input
              type="text"
              required
              value={pairForm.machineFingerprint}
              onChange={(e) => setPairForm({ ...pairForm, machineFingerprint: e.target.value })}
              className="w-full bg-white border border-slate-300 rounded-lg px-3 py-2 text-slate-900 font-mono focus:ring-1 focus:ring-blue-500"
              placeholder="WIN-PC-8921-X64"
            />
            <p className="text-[10px] text-slate-500">
              Unique CPU + Motherboard UUID generated by the Windows Node desktop installer.
            </p>
          </div>

          <div className="p-3 bg-blue-50 border border-blue-200 rounded-lg space-y-1">
            <div className="text-[11px] font-bold text-blue-900">Target Tenant Scope</div>
            <div className="text-[11px] text-blue-800">
              Code: <strong className="font-mono">{currentTenant}</strong> • Branch: {currentBranch}
            </div>
          </div>

          <div className="flex justify-end gap-2 pt-3 border-t border-slate-200">
            <button
              type="button"
              onClick={onClose}
              className="bg-slate-100 text-slate-700 font-bold px-4 py-2 rounded-lg border border-slate-300"
            >
              Cancel
            </button>
            <button
              type="submit"
              className="bg-blue-600 hover:bg-blue-700 text-white font-bold px-5 py-2 rounded-lg shadow-sm transition"
            >
              Authenticate & Pair Node
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
